-- Insert sample projects
INSERT INTO SBOM_PROJECTS (PROJECT_ID, PROJECT_NAME, PROJECT_VERSION, PROJECT_DESCRIPTION, PROJECT_NAMESPACE, SCAN_DATE, SCAN_TOOL, SBOM_FORMAT, SBOM_VERSION, CREATED_AT, UPDATED_AT)
VALUES (1, 'E-Commerce Website', '2.1.0', 'Main e-commerce platform', 'com.company.ecommerce', CURRENT_TIMESTAMP, 'Syft', 'SPDX', '2.3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_PROJECTS (PROJECT_ID, PROJECT_NAME, PROJECT_VERSION, PROJECT_DESCRIPTION, PROJECT_NAMESPACE, SCAN_DATE, SCAN_TOOL, SBOM_FORMAT, SBOM_VERSION, CREATED_AT, UPDATED_AT)
VALUES (2, 'Mobile App Backend', '1.5.3', 'REST API for mobile application', 'com.company.mobile.api', CURRENT_TIMESTAMP, 'CycloneDX', 'CycloneDX', '1.4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_PROJECTS (PROJECT_ID, PROJECT_NAME, PROJECT_VERSION, PROJECT_DESCRIPTION, PROJECT_NAMESPACE, SCAN_DATE, SCAN_TOOL, SBOM_FORMAT, SBOM_VERSION, CREATED_AT, UPDATED_AT)
VALUES (3, 'Data Analytics Platform', '3.0.1', 'Big data processing and analytics', 'com.company.analytics', CURRENT_TIMESTAMP, 'Syft', 'SPDX', '2.3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert sample components
INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (1, 1, 'spring-boot-starter-web', '3.2.0', 'library', 'maven', 'pkg:maven/org.springframework.boot/spring-boot-starter-web@3.2.0', 'https://repo1.maven.org/maven2/', 'https://spring.io/projects/spring-boot', 'Spring Team', 'Apache-2.0', 'Apache-2.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (2, 1, 'jackson-databind', '2.15.2', 'library', 'maven', 'pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.15.2', 'https://repo1.maven.org/maven2/', 'https://github.com/FasterXML/jackson-databind', 'FasterXML', 'Apache-2.0', 'Apache-2.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (3, 1, 'log4j-core', '2.19.0', 'library', 'maven', 'pkg:maven/org.apache.logging.log4j/log4j-core@2.19.0', 'https://repo1.maven.org/maven2/', 'https://logging.apache.org/log4j/', 'Apache Software Foundation', 'Apache-2.0', 'Apache-2.0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (4, 2, 'express', '4.18.2', 'library', 'npm', 'pkg:npm/express@4.18.2', 'https://www.npmjs.com/', 'https://expressjs.com/', 'TJ Holowaychuk', 'MIT', 'MIT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (5, 2, 'lodash', '4.17.19', 'library', 'npm', 'pkg:npm/lodash@4.17.19', 'https://www.npmjs.com/', 'https://lodash.com/', 'John-David Dalton', 'MIT', 'MIT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (6, 3, 'pandas', '1.5.3', 'library', 'pip', 'pkg:pypi/pandas@1.5.3', 'https://pypi.org/', 'https://pandas.pydata.org/', 'The Pandas Development Team', 'BSD-3-Clause', 'BSD-3-Clause', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_COMPONENTS (COMPONENT_ID, PROJECT_ID, COMPONENT_NAME, COMPONENT_VERSION, COMPONENT_TYPE, PACKAGE_MANAGER, PACKAGE_URL, DOWNLOAD_LOCATION, HOMEPAGE, SUPPLIER, LICENSE_CONCLUDED, LICENSE_DECLARED, CREATED_AT, UPDATED_AT)
VALUES (7, 3, 'numpy', '1.24.3', 'library', 'pip', 'pkg:pypi/numpy@1.24.3', 'https://pypi.org/', 'https://numpy.org/', 'NumPy Developers', 'BSD-3-Clause', 'BSD-3-Clause', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert sample vulnerabilities
INSERT INTO SBOM_VULNERABILITIES (VULNERABILITY_ID, COMPONENT_ID, CVE_ID, VULNERABILITY_NAME, DESCRIPTION, SEVERITY, CVSS_SCORE, CWE_ID, REFERENCE_URL, PUBLISHED_DATE, AFFECTED_VERSION, FIXED_VERSION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (1, 5, 'CVE-2021-23337', 'Prototype Pollution in lodash', 'Lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function.', 'HIGH', 7.2, 'CWE-1321', 'https://nvd.nist.gov/vuln/detail/CVE-2021-23337', CURRENT_TIMESTAMP - INTERVAL '30' DAY, '< 4.17.21', '4.17.21', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_VULNERABILITIES (VULNERABILITY_ID, COMPONENT_ID, CVE_ID, VULNERABILITY_NAME, DESCRIPTION, SEVERITY, CVSS_SCORE, CWE_ID, REFERENCE_URL, PUBLISHED_DATE, AFFECTED_VERSION, FIXED_VERSION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (2, 2, 'CVE-2022-42003', 'Jackson Databind Deserialization', 'In FasterXML jackson-databind before 2.13.4, resource exhaustion can occur because of a lack of a check in primitive value deserializers to avoid deep wrapper array nesting.', 'HIGH', 7.5, 'CWE-400', 'https://nvd.nist.gov/vuln/detail/CVE-2022-42003', CURRENT_TIMESTAMP - INTERVAL '60' DAY, '< 2.13.4', '2.13.4', 'FIXED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SBOM_VULNERABILITIES (VULNERABILITY_ID, COMPONENT_ID, CVE_ID, VULNERABILITY_NAME, DESCRIPTION, SEVERITY, CVSS_SCORE, CWE_ID, REFERENCE_URL, PUBLISHED_DATE, AFFECTED_VERSION, FIXED_VERSION, STATUS, CREATED_AT, UPDATED_AT)
VALUES (3, 3, 'CVE-2021-44228', 'Log4j RCE Vulnerability', 'Apache Log4j2 <=2.14.1 JNDI features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints.', 'CRITICAL', 10.0, 'CWE-502', 'https://nvd.nist.gov/vuln/detail/CVE-2021-44228', CURRENT_TIMESTAMP - INTERVAL '90' DAY, '< 2.15.0', '2.15.0', 'FIXED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);